config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'repositories#new'
  get "result", to: "repositories#repo"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  require 'open-uri'

  def new; end

  def repo
    @repo = params[:repo]
    @user = params[:user]
    @result = api(@user, @repo)
  end

  private

  def api(user, repo)
    begin
      response = URI.open("https://api.github.com/repos/#{user}/#{repo}")
    rescue
    else
      JSON.parse(response.read)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubRepositories</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/new.html.erb
<%= form_tag result_path, method: :get do %>
  <%= text_field_tag :user,
    params[:user],
    class: "form-control",
    placeholder: "Username"
  %>
  <%= text_field_tag :repo,
    params[:repo],
    class: "form-control",
    placeholder: "Repository"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/repositories/repo.html.erb
<% if @result %>
  <h4>Repo Name: </h4> <p><%= @result["name"] %></p>
  <h4>Username: </h4><p><%= @result["owner"]["login"] %></p>
  <h4>Language: </h4><p><%= @result["language"] %></p>
  <h4>URL: </h4><a href=<%= @result["html_url"] %>><%= @result["html_url"] %></a>
<% else %>
  <h3>Sorry but the repository "<%=@repo%>" in combination with the user "<%=@user%>" does not exist.</h3>
<% end %>
<br>
<br>
<strong>**<%= link_to "Search again", root_path %>**</strong>